[package]
name = "nextcall"
version = "0.1.0"
edition = "2024"

[dependencies]
ical = "0.11.0"
reqwest = { version = "0.12.23", features = ["blocking"] }
chrono = "0.4"
objc2 = "0.5"
objc2-foundation = { version = "0.2", features = ["NSString", "NSThread", "NSArray"] }
objc2-app-kit = { version = "0.2", features = ["NSAlert", "NSWindow", "NSTextField", "NSButton", "NSPanel"] }
core-foundation = "0.9"
core-foundation-sys = "0.8"
tray-icon = "0.14.3"
winit = "0.29.15"
image = "0.25.0"
imageproc = "0.25.0"
ab_glyph = "0.2"
mac-notification-sys = "0.6.1"
open = "5.0"
